# This is a basic workflow to help you get started with Actions

name: Publish Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  draft-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.package-version.outputs.current-version }}
          allowUpdates: true
          draft: true
          commit: ${{ github.sha }}
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 16.x
      - run: npm install    
      - run: npm run build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "htp1-custom-ui-background-service-*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.package-version.outputs.current-version }}
          allowUpdates: true
          draft: true
          commit: ${{ github.sha }}
